- hosts: localhost

  tasks:
    - name: build xmpp binary
      shell: "sbcl --eval \"(ql:quickload 'mentat)\" --eval \"(mentat::save-image)\""

- hosts: botservers

  vars:
    username: octocat
    xmpp_binary_name: mentat-xmpp-bot
    xmpp_upstart_conf: mentat-xmpp.conf

  tasks:

    - name: install mongo on remote server
      apt: name=mongodb state=present
      sudo: yes

    - name: copy Upstart conf for xmpp bot
      copy: src=./xmpp-service.conf dest=/etc/init/{{ xmpp_upstart_conf }}
      sudo: yes

    - name: stat old xmpp remote binary
      stat: path=/home/{{ username }}/{{ xmpp_binary_name }}
      register: xmpp_binary_stat

    - name: remove old xmpp remote binary
      command: rm /home/{{ username }}/{{ xmpp_binary_name }}
      when: xmpp_binary_stat.stat.exists

    - name: copy compiled xmpp binary to remote server
      copy: src=./{{ xmpp_binary_name }} dest=/home/{{ username }}

    - name: copy bot config to remote server
      copy: src=./src/config.lisp dest=/home/{{ username }}

    - name: set xmpp binary attrs
      file: path=./{{ xmpp_binary_name }} mode=u+rwx

    - name: check if mongodb is up and running on remote server
      service: name=mongodb state=started
      sudo: yes

    - name: restart mentat-xmpp service on remote server
      service: name=mentat-xmpp state=restarted
      sudo: yes
