- include: preprocess.yaml

- hosts: localhost
  gather_facts: no

  tasks:
    - include_vars: common_vars.yml

    # TODO: exclude Quicklisp, see:
    # https://www.darkchestnut.com/2016/dont-put-quicklisp-in-your-binary-just-because-a-library-demands-it/
    # https://www.darkchestnut.com/2016/keep-quicklisp-and-qlot-out-of-your-application-binary/
    - name: build notifier binary
      shell: "sbcl --eval \"(ql:quickload 'mentat-notifier)\" --eval \"(mentat-notifier::save-image-notifier)\""

- hosts: botservers
  gather_facts: no

  tasks:
    - include_vars: common_vars.yml

    - name: remove old notifier remote binary
      file:
        path=/home/{{ username }}/{{ notifier_binary_name }}
        state=absent

    - name: copy compiled notifier binary to remote server
      copy: src=../deploy/{{ notifier_binary_name }} dest=/home/{{ username }}

    - name: copy notifier config to remote server
      copy: src=../src/notifier/config.lisp dest=/home/{{ username }}/notifier-config.lisp

    - name: set notifier binary attrs
      file: path=/home/{{ username }}/{{ notifier_binary_name }} mode=u+rwx

    - name: restart mentat-notifier service on remote server
      supervisorctl: name=mentat-notifier state=restarted
      become: yes
      when: False  #FIXME: check if service is actually running and then remove hardcode

- hosts: localhost

  tasks:
    - name: cleanup recently built binary
      file: path=./mentat-notifier state=absent

- include: postprocess.yaml
