- hosts: localhost
  gather_facts: no

  tasks:
    - include_vars: common_vars.yml

    - name: instantiate supervisor conf template
      template: src=../conf/supervisor.conf dest=./supervisor.conf

- hosts: botservers

  tasks:
    - include_vars: common_vars.yml

    - name: install packages on remote server
      apt: name={{ item }} state=present
      with_items:
        - mongodb
        - supervisor
        - logrotate
      become: yes

    - name: check if supervisor daemon is running
      service: name=supervisor state=started
      become: yes

    - name: check if mongodb is up and running on remote server
      service: name=mongodb state=started
      become: yes

    - name: copy supervisor conf
      copy: src=./supervisor.conf dest=/etc/supervisor/conf.d/{{ supervisor_conf }}
      become: yes

    - name: copy mentat config to remote server
      copy: src=../src/config.lisp dest=/home/{{ username }}
